version: 2

multi-ecosystem-groups:
  tauri:
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
      tailwindcss:
        patterns:
          - tailwindcss
          - "@tailwindcss/*"

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo

  - package-ecosystem: npm
    directory: /
    multi-ecosystem-group: tauri
    patterns:
      - "@tauri-apps/*"

  - package-ecosystem: cargo
    directory: /src-tauri
    multi-ecosystem-group: tauri
    patterns:
      - tauri
      - tauri-*
