[tools]
actionlint = "latest"
ghalint = "latest"
lefthook = "latest"
node = "lts"
rust = "latest"
shellcheck = "latest"
task = "latest"
tombi = "latest"
viteplus = "latest"
zizmor = "latest"

[hooks]
postinstall = "lefthook install"
