[plugins]
vite-plus = "https://github.com/markmals/mise-vite-plus"

[tools]
actionlint = "latest"
ghalint = "latest"
lefthook = { version = "latest", postinstall = "lefthook install" }
node = "lts"
rust = "latest"
shellcheck = "latest"
task = "latest"
tombi = "latest"
vite-plus = "latest"
zizmor = "latest"
