[bootstrap.mise_shell_activate]
bashrc = true
zshrc = true

[plugins]
vite-plus = "https://github.com/markmals/mise-vite-plus"

[tools]
actionlint = "latest"
ghalint = "latest"
jq = "latest"
lefthook = "latest"
rust = { version = "latest", components = "clippy" }
shellcheck = "latest"
task = "latest"
tombi = "latest"
vite-plus = "latest"
zizmor = "latest"

[hooks]
postinstall = "lefthook install"
