version: 3

tasks:
  default:
    cmd: task -l
    silent: true

  build:clean:
    desc: Clean build artifacts
    dir: src-tauri
    cmd: cargo clean
    silent: true

  build:release:
    desc: Perform release build
    deps:
      - build:clean
    env:
      VITE_MODE: production
      TAURI_SIGNING_PRIVATE_KEY: "{{.ROOT_DIR}}/.tauri/updater.key"
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD:
    cmds:
      - cmd: git switch main
      - cmd: git pull
      - cmd: pnpm install --frozen-lockfile
      - cmd: pnpm run tauri build
      - cmd: git switch -
    silent: true

  build:publish:
    desc: Publish release build artifacts
    deps:
      - build:release
    platforms:
      - windows
    vars:
      VERSION:
        sh: cargo metadata --format-version=1 --no-deps | jq -r ".packages[0].version"
      OWNER:
        sh: gh repo view --json owner --jq ".owner.login"
      TAG: v{{.VERSION}}
      REPOSITORY: "{{.OWNER}}/tauri-app-release"
    dir: src-tauri
    cmds:
      - cmd: git switch main
      - cmd: |
          powershell -Command '
            Set-Location target/release
            $assets = Get-ChildItem bundle "*_{{.VERSION}}_*" -Recurse | Select-Object -ExpandProperty FullName
            $signatureFile = $assets | Where-Object { $_ -Like "*_{{.VERSION}}_*.msi.sig" }
            $signature = (Get-Content $signatureFile -Raw).Trim()
            Invoke-Expression "gh release download {{.TAG}} -p latest.json --clobber -R {{.REPOSITORY}}"
            $jsonFile = Convert-Path latest.json
            $json = Get-Content $jsonFile -Raw | ConvertFrom-Json
            $json.platforms."windows-x86_64".signature = $signature
            ConvertTo-Json $json -Depth 100 | Set-Content $jsonFile
            Invoke-Expression "pnpm dlx prettier --write $jsonFile"
            $assets += $jsonFile 
            $assets = $assets | ForEach-Object { "`"$_`"" }
            Invoke-Expression "gh release upload {{.TAG}} $assets --clobber -R {{.REPOSITORY}}"
            Invoke-Expression "gh release edit {{.TAG}} --draft=false --latest -R {{.REPOSITORY}}"
          '
      - cmd: git switch -
    silent: true
