version: 3

tasks:
  default:
    cmd: task -l
    silent: true

  build:clean:
    desc: ビルド成果物を削除する
    dir: src-tauri
    cmd: cargo clean
    silent: true

  build:release:
    desc: リリースビルドを実行する
    env:
      VITE_MODE: production
      TAURI_SIGNING_PRIVATE_KEY: "{{.ROOT_DIR}}/.tauri/updater.key"
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD:
    deps: [build:clean]
    cmds:
      - cmd: git switch main
      - cmd: git pull
      - cmd: pnpm install --frozen-lockfile
      - cmd: pnpm run tauri build
      - cmd: git switch -
    silent: true

  build:publish:
    desc: リリースビルドの成果物を公開する
    deps: [build:release]
    platforms: [windows]
    dir: src-tauri
    cmds:
      - cmd: git switch main
      - cmd: |
          powershell -Command '
            $assets = Get-ChildItem target/release/bundle *_{{.VERSION}}_* -Recurse | ForEach-Object { "`"$($_.FullName)`"" }
            Invoke-Expression "gh release upload v{{.VERSION}} $assets --clobber -R {{.OWNER}}/tauri-app-release"
          '
      - cmd: git switch -
    vars:
      VERSION:
        sh: cargo metadata --format-version=1 --no-deps | jq -r ".packages[0].version"
      OWNER:
        sh: gh repo view --json owner --jq ".owner.login"
    silent: true
