name: npm audit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5"
      timezone: Asia/Tokyo

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-slim
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: jdx/mise-action@v4.2.5
        with:
          install_args: node

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        uses: oke-py/npm-audit-action@v5.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dedupe_comments: true
          dedupe_issues: true
          report_format: markdown
