name: Release Application

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    env:
      CARGO_TERM_COLOR: always
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - macos-26-intel
          - windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Set up Node.js and Rust
        uses: jdx/mise-action@v4.3.0
        with:
          install_args: >-
            node
            rust

      - name: Set up pnpm and install frontend dependencies
        uses: pnpm/setup@v2.0.2

      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2.9.2
        with:
          workspaces: src-tauri

      - name: Build and release application
        id: build
        uses: tauri-apps/tauri-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          VITE_MODE: production
          TAURI_SIGNING_PRIVATE_KEY: ${{ github.workspace }}/.tauri/updater.key
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseBody: v__VERSION__ release
          releaseDraft: true
          owner: ${{ github.repository_owner }}
          repo: tauri-app-release
          releaseCommitish: main

      - name: Create Windows portable asset
        if: runner.os == 'Windows'
        run: |
          ConvertFrom-Json '${{ steps.build.outputs.artifactPaths }}' | ForEach-Object {
              if ((Split-Path $_ -Leaf) -match '(.+)-setup\.exe$') {
                  $asset = Join-Path $PWD "$($Matches[1]).zip"
                  Compress-Archive *.exe,third-party $asset
                  echo "WINDOWS_PORTABLE_ASSET=$asset" >> $env:GITHUB_ENV
              }
          }
        working-directory: src-tauri/target/release

      - name: Release Windows portable asset
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v3.0.3
        with:
          tag_name: v${{ steps.build.outputs.appVersion }}
          files: ${{ env.WINDOWS_PORTABLE_ASSET }}
          repository: ${{ github.repository_owner }}/tauri-app-release
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Create tag
        uses: softprops/action-gh-release@v3.0.3
        with:
          tag_name: v${{ steps.build.outputs.appVersion }}
          body: v${{ steps.build.outputs.appVersion }} release
