name: Rust Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1 libxdo-dev libayatana-appindicator3-dev libasound2-dev

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo2junit
        run: cargo install cargo2junit

      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        env:
          RUSTC_BOOTSTRAP: 1
        working-directory: src-tauri
        run: |
          cargo test -- -Z unstable-options --format json | tee test-results.json
          cat test-results.json | cargo2junit > test-results.xml

      - name: Publish test report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: src-tauri/test-results.xml
          check_name: Test Report
          detailed_summary: true
          include_passed: true

      # - name: Run Clippy
      #   working-directory: src-tauri
      #   run: cargo clippy --all-targets --all-features
