name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  webview-test:
    name: WebView Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up pnpm and install frontend dependencies
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0

      - name: Run tests
        run: >-
          pnpm run test
          --reporter=default
          --reporter=junit

      - name: Publish test report
        if: always()
        uses: ctrf-io/github-test-reporter@7974087018bf4857cf5a9d78723e152038c3fa31 # v1.3.0
        with:
          report-path: .vitest/junit/output.xml
          title: WebView Test Report
          use-suite-name: true
          integrations-config: |
            {
              "junit-to-ctrf": {
                "enabled": true
              }
            }

  rust-test:
    name: Rust Test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    defaults:
      run:
        working-directory: src-tauri

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libayatana-appindicator3-dev \
            libwebkit2gtk-4.1-dev

      - name: Set up Rust
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install_args: rust

      - name: Install Rust development tools
        uses: taiki-e/install-action@e67fa11c4b9316fa714ddf0abed07a0c3143b95b # v2.87.4
        with:
          tool: cargo-nextest

      - name: Configure Rust cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          workspaces: src-tauri

      - name: Run Clippy
        uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
        with:
          filter_mode: nofilter

      - name: Run tests
        run: cargo nextest run --profile ci

      - name: Publish test report
        if: always()
        uses: ctrf-io/github-test-reporter@7974087018bf4857cf5a9d78723e152038c3fa31 # v1.3.0
        with:
          report-path: src-tauri/target/nextest/ci/junit.xml
          title: Rust Test Report
          use-suite-name: true
          integrations-config: |
            {
              "junit-to-ctrf": {
                "enabled": true
              }
            }
