name: Run Tests

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libayatana-appindicator3-dev \
            libwebkit2gtk-4.1-dev

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm and frontend dependencies
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Rust development tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo2junit

      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      # - name: Run WebView tests
      #   run: pnpm test

      # - name: Publish WebView test report
      #   uses: ctrf-io/github-test-reporter@v1
      #   with:
      #     report-path: ctrf/ctrf-report.json
      #     title: WebView Test Report

      - name: Run Clippy
        uses: giraffate/clippy-action@v1
        env:
          CARGO_INCREMENTAL: 1
        with:
          workdir: src-tauri
          filter_mode: nofilter

      - name: Run Rust tests
        env:
          CARGO_INCREMENTAL: 1
          RUSTC_BOOTSTRAP: 1
        working-directory: src-tauri
        run: cargo test -- -Z unstable-options --format json | cargo2junit > rust-test-results.xml

      - name: Publish Rust test report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: src-tauri/rust-test-results.xml
          title: Rust Test Report
          integrations-config: |
            {
              "junit-to-ctrf": {
                "enabled": true,
                "options": {
                  "output": "rust-test-results.json",
                  "useSuiteName": false
                }
              }
            }
